### ISSUE TITLE
.jpg.exporting filetype crashes script

### ISSUE THREAD

**Issue by dguzzo** [dguzzo/RMagick-Blend#23]
such as when exporting from iPhoto and the script is run before the images in the pool directory are finished.

```
Dominicks-iMac:RMagickBlend dominick$ ruby make-blends.rb 
loaded "batch 18" settings
~~~~~ABOUT TO BLEND~~~~~
running batch 1 of 8...
/Users/dominick/.rvm/gems/ruby-2.1.5/gems/rmagick-blend-4.1.0/lib/rmagick-blend/file_utils.rb:38:in `read': no decode delegate for this image format `./batch-18-pool/IMG_0553.jpg.exporting' @ error/constitute.c/ReadImage/550 (Magick::ImageMagickError)
	from /Users/dominick/.rvm/gems/ruby-2.1.5/gems/rmagick-blend-4.1.0/lib/rmagick-blend/file_utils.rb:38:in `get_imagemagick_pair'
	from /Users/dominick/.rvm/gems/ruby-2.1.5/gems/rmagick-blend-4.1.0/lib/rmagick-blend/compositing.rb:24:in `composite_images'
	from /Users/dominick/.rvm/gems/ruby-2.1.5/gems/rmagick-blend-4.1.0/lib/rmagick-blend.rb:40:in `block in create_blends'
	from /Users/dominick/.rvm/gems/ruby-2.1.5/gems/rmagick-blend-4.1.0/lib/rmagick-blend.rb:38:in `times'
	from /Users/dominick/.rvm/gems/ruby-2.1.5/gems/rmagick-blend-4.1.0/lib/rmagick-blend.rb:38:in `create_blends'
	from make-blends.rb:4:in `<main>'

```

**Comment by dguzzo** [comment]
seems fixed, not sure if a previous commit incidentally fixed it. or at least it doesn't occur in my contrived test with artificial .jpg.exporting files.
